apiVersion: v1
kind: Service
metadata:
  name: static-site-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: static-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
