frontend:
  image:
    repository: 221082179535.dkr.ecr.us-east-1.amazonaws.com/unilink/artifacts/client_image
    tag: d453d71a4c8003a5fc7c808e95b594ee9ab20ed6
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80



backend:
  image:
    repository: 774305587934.dkr.ecr.us-east-1.amazonaws.com/unilink/artifacts/server_image
    tag: e3d56b30b044d9cf6d0cefebb60eb6aeac7f56ef
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3001
