frontend:
  image:
    repository: 774305587934.dkr.ecr.us-east-1.amazonaws.com/unilink/artifacts/client_image
    tag: be46f4efca0b1a351f43805c7fd9b368bf0db336
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80



backend:
  image:
    repository: 774305587934.dkr.ecr.us-east-1.amazonaws.com/unilink/artifacts/server_image
    tag: e11e6381848283459ca62a9aed16300fafba5ad5
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3001
