frontend:
  image:
    repository: booraraman/frontend-image
    tag: 
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80



backend:
  image:
    repository: 221082179535.dkr.ecr.us-east-1.amazonaws.com/unilink/artifacts/server_image
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3001
