replicaCount: 2

image:
  repository: 221082179535.dkr.ecr.us-east-1.amazonaws.com/development
  tag: 74fbe8c9e0458172abd67c9c078712cad5242817
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources: {}
