frontend:
  image:
    repository: <your-frontend-ecr-url>
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80

backend:
  image:
    repository: <your-backend-ecr-url>
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3001