replicaCount: 2

image:
  repository: 221082179535.dkr.ecr.us-east-1.amazonaws.com/development
  tag: 3a586021ba54a0177158cf105edae1650ab1555b
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources: {}
