replicaCount: 2

image:
  repository: 221082179535.dkr.ecr.us-east-1.amazonaws.com/development
  tag: f60fd218be9995695f1efe183422cbcfde560812
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources: {}
