apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.elastic.co'
    chart: elasticsearch
    targetRevision: 7.17.3  # Or latest supported by Helm repo
    helm:
      values: |
        {{ .Files.Get "efk/elasticsearch/values.yaml" }}
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
