name: DevelopmentCI2

on:
  push:
    branches:
      - main
    paths:
      - 'Development/**'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: development
  AWS_ACCOUNT_ID: 221082179535
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_IMAGE: ""  # Will be set dynamically

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker image name
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "DOCKER_IMAGE=portfolio-nginx:${SHORT_SHA}" >> $GITHUB_ENV

      - name: Login to Amazon ECR using AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.AWS_REGION }}
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
            
      - name: Build Docker image
        run: |
          docker build -t "${{ env.DOCKER_IMAGE }}" ./Development

      - name: Tag Docker image for ECR
        run: |
          ECR_IMAGE="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}/$(echo ${{ env.DOCKER_IMAGE }})"
          echo "ECR_IMAGE=$ECR_IMAGE" >> $GITHUB_ENV
          docker tag "${{ env.DOCKER_IMAGE }}" "$ECR_IMAGE"

      - name: Push Docker image to ECR
        run: |
          docker push "${{ env.ECR_IMAGE }}"
