name: DevelopmentCI2

on:
  push:
    branches:
      - main
    paths:
      - 'Development/**'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: development
  AWS_ACCOUNT_ID: 221082179535
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_IMAGE: ""  # Will be set dynamically

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker image name
        run: |
          # Use a user-friendly tag format, e.g., v1.0.0-short_SHA
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          VERSION="v1.0.0"  # You can adjust this version or make it dynamic based on tags
          echo "DOCKER_IMAGE=${{ env.ECR_REPOSITORY }}:${VERSION}-${SHORT_SHA}" >> $GITHUB_ENV
          echo "Docker image name: ${{ env.DOCKER_IMAGE }}"

      - name: Login to Amazon ECR using AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.AWS_REGION }}
          # Get login password and authenticate Docker with ECR
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
            
      - name: Build Docker image
        run: |
          docker build -t "${{ env.DOCKER_IMAGE }}" ./Development
          echo "Docker build complete."

      - name: Tag Docker image for ECR
        run: |
          # ECR image full path
          ECR_IMAGE="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.DOCKER_IMAGE }}"
          echo "ECR_IMAGE=$ECR_IMAGE" >> $GITHUB_ENV
          # Tag the Docker image for ECR
          docker tag "${{ env.DOCKER_IMAGE }}" "$ECR_IMAGE"
          echo "Docker image tagged as: $ECR_IMAGE"

      - name: Push Docker image to ECR
        run: |
          # Push the image to the ECR repository
          docker push "${{ env.ECR_IMAGE }}"
          echo "Docker push complete."
