name: Update Values

on:
  workflow_run:
    workflows: ["DevelopmentCI2"]  # Make sure this exactly matches the name: field in the source workflow
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  download-image-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Download image-tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag  # must match the uploaded artifact name exactly

      - name: Print image tag
        run: |
          echo "Downloaded tag:"
          cat image_tag.txt

      - name: Read image tag and export as env
        id: tag
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Using image tag: $IMAGE_TAG"

      - name: Update values.yaml file
        run: |
          sed -i "s|\(tag: \).*|\1${{ env.IMAGE_TAG }}|" Deployments/values.yaml
          echo "Updated image tag in values.yaml to: ${{ env.IMAGE_TAG }}"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Deployments/values.yaml
          git commit -m "chore: update image tag in values.yaml to ${{ env.IMAGE_TAG }}"
          git push
